tasks:
    - name: "init eliza env"
      init: |
          nvm install v23.3.0
          nvm use v23.3.0
          git clone https://github.com/dforce-network/elizaos-plugin-intenet packages/plugin-intenet
          pnpm add "@elizaos/core@workspace:*" --filter ./packages/plugin-intenet/
          pnpm add "@elizaos-plugins/plugin-intenet@workspace:*" --filter ./agent
          cp .env.example .env
      command: pnpm install --no-frozen-lockfile && pnpm build
